services:
  realtors_app:
    image: realtors_app:latest
    container_name: realtors_app_container
    ports:
      - 7860:7860
    volumes:
      - .env:/app/.env
    networks:
      - realtors_app_network
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis_container
    networks:
      - realtors_app_network
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

networks:
  realtors_app_network:
    driver: bridge

volumes:
  redis_data:
