"""add forign keys 

Revision ID: 4a7093bb1604
Revises: 99842fe6d43c
Create Date: 2025-03-11 13:10:12.546403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a7093bb1604'
down_revision: Union[str, None] = '99842fe6d43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('n8n_chat_histories_signup')
    op.drop_table('n8n_chat_histories_buyer')
    op.drop_table('n8n_chat_histories_listing')
    op.alter_column('bookings', 'listing_agent_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'bookings', 'users', ['listing_agent_phone_number'], ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.alter_column('bookings', 'listing_agent_phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('n8n_chat_histories_listing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='n8n_chat_histories_listing_pkey')
    )
    op.create_table('n8n_chat_histories_buyer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='n8n_chat_histories_buyer_pkey')
    )
    op.create_table('n8n_chat_histories_signup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='n8n_chat_histories_signup_pkey')
    )
    # ### end Alembic commands ###
