"""chnage table name 

Revision ID: 99842fe6d43c
Revises: cb47c64c7f61
Create Date: 2025-03-06 12:16:39.023784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99842fe6d43c'
down_revision: Union[str, None] = 'cb47c64c7f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('active_session_id', sa.String(), nullable=True),
    sa.Column('queued_session_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('completed_session_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_agent_phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('mls_number', sa.String(), nullable=True),
    sa.Column('buyer_selected_date', sa.String(), nullable=True),
    sa.Column('buyer_selected_time', sa.String(), nullable=True),
    sa.Column('listing_selected_date', sa.String(), nullable=True),
    sa.Column('listing_selected_time', sa.String(), nullable=True),
    sa.Column('listing_agent_phone_number', sa.String(), nullable=True),
    sa.Column('listing_agent_session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_agent_phone_number'], ['users.phone_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
