"""modify columns names

Revision ID: 9d29bbc9c6d0
Revises: ce2d2fb737b6
Create Date: 2025-03-03 17:01:30.810691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d29bbc9c6d0'
down_revision: Union[str, None] = 'ce2d2fb737b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('buyer_selected_date', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('buyer_selected_time', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('listing_selected_date', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('listing_selected_time', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('properties', 'time')
    op.drop_column('properties', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'status')
    op.drop_column('properties', 'listing_selected_time')
    op.drop_column('properties', 'listing_selected_date')
    op.drop_column('properties', 'buyer_selected_time')
    op.drop_column('properties', 'buyer_selected_date')
    # ### end Alembic commands ###
