"""add colmuns 

Revision ID: cb47c64c7f61
Revises: 9d29bbc9c6d0
Create Date: 2025-03-04 16:07:14.749129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb47c64c7f61'
down_revision: Union[str, None] = '9d29bbc9c6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_session_id', sa.String(), nullable=True))
    op.drop_column('users', 'current_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'active_session_id')
    # ### end Alembic commands ###
